nimble/host: Remove redundant check in connection latency
apache/mynewt-nimble pull request #1000
Opened 2021-07-15 09:52 UTC by prasad-alatkar

## Fix redundant check when extended advertisement flag is enabled.

In `ble_gap.c`, as `params->latency` is of `unsigned uint16_t` type and `BLE_HCI_CONN_LATENCY_MIN` is `0`, the check `(params->latency < BLE_HCI_CONN_LATENCY_MIN)` will always be false and hence can be dropped.

This can give below warnings if custom compiler options are used while compiling the code.
```
warning: comparison is always false due to limited range of data type [-Wtype-limits]
```

2021-07-21 09:27 UTC, rymanluk requested changes
Looks good. Please just update commit message with the information that params->latency is uint16_t and BLE_HCI_CONN_LATENCY_MIN is 0 which is why we can drop it.

2021-07-26 05:11 UTC, prasad-alatkar commented
> Looks good. Please just update commit message with the information that params->latency is uint16_t and BLE_HCI_CONN_LATENCY_MIN is 0 which is why we can drop it.

Thanks @rymanluk. Done!!

2021-08-24 12:25 UTC, rahult-github commented
Hi @rymanluk , Can you please help merge if there are no further comments ? 

> > Looks good. Please just update commit message with the information that params->latency is uint16_t and BLE_HCI_CONN_LATENCY_MIN is 0 which is why we can drop it.
> 
> Thanks @rymanluk. Done!!

2022-04-13 10:03 UTC, sjanc approved these changes

2022-04-13 10:03 UTC, merged