host/ble_att_srv: security check for notifications/indications
apache/mynewt-nimble pull request #1223
Opened 2022-03-28 06:50 UTC by KKopyscinski

According to Core Specification Version 5.3, Vol 3, Part C
10.3.2.2: " Any notifications received before the security requirements
are met shall be ignored. Any indications received before the security
requirements are met shall be confirmed and then discarded. When a
client reconnects to a server and expects to receive indications or
notifications for which security is required, the client shall enable
encryption with the server."

2022-03-28 06:52 UTC, KKopyscinski commented
this is affecting
GAP/SEC/SEM/BV-56-C
GAP/SEC/SEM/BV-57-C
GAP/SEC/SEM/BV-59-C
GAP/SEC/SEM/BV-60-C

2022-04-07 10:27 UTC, sjanc requested changes

2022-04-07 10:27 UTC, sjanc commented on nimble/host/src/ble_att_svr.c
> +    if (MYNEWT_VAL(BLE_SM_SC_LVL) >= 2 && !sec_state.encrypted) {
I think this needs verification per security level ie MITM and LESC too

2022-04-13 08:40 UTC, sjanc approved these changes

2022-04-13 08:41 UTC, merged