nimble/gatts: Add check for RFU bits
apache/mynewt-nimble pull request #1660
Opened 2023-12-12 03:54 UTC by Roshan23699

Add Reserved For Future use bits check(needed for PTS)

2023-12-12 03:55 UTC, Roshan23699 commented
@sjanc PTAL

2023-12-19 11:04 UTC, sjanc requested changes
@KKopyscinski could you have a look at ble_gatts_peer_cl_sup_feat_update usage?

there is something fishy with that code,   firstly it probably shouldn't be in public gatt header, secondly,  returned value is used at ATT code while it return BLE_HS codes

This should be cleaned up, maybe simply returning BLE_ATT_ERR_UNLIKELY and/or BLE_ATT_ERR_INSUFFICIENT_RES instead of BLE_HS would be enough?

2023-12-20 09:15 UTC, Roshan23699 commented on nimble/host/src/ble_gatts.c
> +    uint8_t rfu_mask = 7;
This, macro I defined just below BLE_GATT_CHR_CLI_SUP_FEAT_SZ in ble_gatt_priv.h file. 
I cannot define this in gatt service file(ble_svc_gatt.h) as the services are not accessible in src/host.

2023-12-20 09:16 UTC, Roshan23699 commented on nimble/host/src/ble_gatts.c
> +                rc = BLE_ATT_ERR_VALUE_NOT_ALLOWED;
Returning all att errors should work. Could you take a look again? I converted all the HS errors to ATT.

2023-12-22 14:17 UTC, sjanc approved these changes

2023-12-22 14:17 UTC, merged