nimble/audio/bass: Modify remove source operation
apache/mynewt-nimble pull request #1839
Opened 2024-08-09 10:05 UTC by szymon-czapracki

Fix event type in ble_audio_event structure.
Modify data for use with new mbuf.
Add characteristic value in receive state.
Remove goto pointing to goto itself.

2024-08-19 14:08 UTC, MariuszSkamra requested changes

2024-08-22 15:11 UTC, szymon-czapracki commented on nimble/host/audio/services/bass/src/ble_audio_svc_bass.c
> +	operation.op = BLE_SVC_AUDIO_BASS_OPERATION_REMOVE_SOURCE;
Done

2024-08-22 15:11 UTC, szymon-czapracki commented on nimble/host/audio/services/bass/src/ble_audio_svc_bass.c
> +	rcv_state->chr_val = chr_val;
Done

2024-08-26 09:47 UTC, rymanluk approved these changes

2024-09-02 07:02 UTC, sjanc approved these changes

2024-09-02 07:03 UTC, merged