Mesh sync March 2021
apache/mynewt-nimble pull request #958
Opened 2021-04-02 05:22 UTC by KKopyscinski

2021-05-14 11:52 UTC, KKopyscinski commented
Results of Mesh tests with these patches:

<details>

  1/227   MESH    MESH/NODE/PBADV/BV-01-C       PASS            64.082                  
  2/227   MESH    MESH/NODE/PBADV/BV-02-C       PASS            160.139                  
  3/227   MESH    MESH/NODE/PBADV/BV-03-C       PASS            27.5                  
  4/227   MESH    MESH/NODE/PBADV/BV-04-C       PASS            27.582                  
  5/227   MESH    MESH/NODE/PBADV/BI-01-C       PASS            62.303                  
  6/227   MESH    MESH/NODE/PBADV/BI-02-C       PASS            26.42                  
  7/227   MESH    MESH/NODE/PBADV/BI-03-C       PASS            58.035                  
  8/227   MESH    MESH/NODE/PBADV/BI-04-C       PASS            56.464                  
  9/227   MESH    MESH/NODE/MPS/BV-01-C         PASS            24.989                  
 10/227   MESH    MESH/NODE/MPS/BV-02-C         PASS            27.5                  
 11/227   MESH    MESH/NODE/MPS/BV-03-C         PASS            34.645                  
 12/227   MESH    MESH/NODE/MPS/BV-04-C         PASS            30.86                  
 13/227   MESH    MESH/NODE/MPS/BV-05-C         PASS            31.001                  
 14/227   MESH    MESH/NODE/MPS/BV-06-C         PASS            31.994                  
 15/227   MESH    MESH/NODE/MPS/BV-07-C         PASS            30.465                  
 16/227   MESH    MESH/NODE/MPS/BV-08-C         PASS            27.793                  
 17/227   MESH    MESH/NODE/MPS/BV-09-C         PASS            29.208                  
 18/227   MESH    MESH/NODE/MPS/BV-10-C         PASS            28.36                  
 19/227   MESH    MESH/NODE/MPS/BI-01-C         PASS            27.496                  
 20/227   MESH    MESH/NODE/PROV/BV-01-C        PASS            34.732                  
 21/227   MESH    MESH/NODE/PROV/BV-07-C        PASS            31.041                  
 22/227   MESH    MESH/NODE/PROV/BV-09-C        PASS            208.679                  
 23/227   MESH    MESH/NODE/PROV/BV-10-C        PASS            48.554                  
 24/227   MESH    MESH/NODE/PROV/BV-11-C        PASS            45.528                  
 25/227   MESH    MESH/NODE/PROV/BV-12-C        PASS            45.637                  
 26/227   MESH    MESH/NODE/PROV/BI-01-C        PASS            27.78                  
 27/227   MESH    MESH/NODE/PROV/BI-02-C        PASS            51.041                  
 28/227   MESH    MESH/NODE/PROV/BI-03-C        PASS            38.026                  
 29/227   MESH    MESH/NODE/PROV/BI-13-C        PASS            41.336                  
 30/227   MESH    MESH/NODE/PROV/BI-15-C        PASS            28.359                  
 31/227   MESH    MESH/NODE/BCN/SNB/BV-01-C     PASS            45.728                  
 32/227   MESH    MESH/NODE/NET/BV-01-C         PASS            35.322                  
 33/227   MESH    MESH/NODE/NET/BV-02-C         PASS            35.651                  
 34/227   MESH    MESH/NODE/NET/BV-03-C         PASS            34.464                  
 35/227   MESH    MESH/NODE/NET/BV-04-C         PASS            35.872                  
 36/227   MESH    MESH/NODE/NET/BV-05-C         PASS            36.301                  
 37/227   MESH    MESH/NODE/NET/BV-06-C         PASS            36.075                  
 38/227   MESH    MESH/NODE/NET/BV-07-C         PASS            34.361                  
 39/227   MESH    MESH/NODE/NET/BV-08-C         PASS            32.3                  
 40/227   MESH    MESH/NODE/NET/BV-09-C         PASS            32.053                  
 41/227   MESH    MESH/NODE/NET/BV-10-C         PASS            33.129                  
 42/227   MESH    MESH/NODE/NET/BV-11-C         PASS            32.459                  
 43/227   MESH    MESH/NODE/NET/BV-12-C         PASS            32.185                  
 44/227   MESH    MESH/NODE/NET/BV-13-C         PASS            33.193                  
 45/227   MESH    MESH/NODE/NET/BV-14-C         PASS            34.185                  
 46/227   MESH    MESH/NODE/NET/BI-01-C         PASS            33.973                  
 47/227   MESH    MESH/NODE/NET/BI-02-C         PASS            46.085                  
 48/227   MESH    MESH/NODE/NET/BI-03-C         PASS            31.583                  
 49/227   MESH    MESH/NODE/RLY/BV-01-C         PASS            62.2                  
 50/227   MESH    MESH/NODE/RLY/BV-02-C         PASS            100.736                  
 51/227   MESH    MESH/NODE/RLY/BI-01-C         PASS            34.945                  
 52/227   MESH    MESH/NODE/RLY/BI-02-C         PASS            41.493                  
 53/227   MESH    MESH/NODE/TNPT/BV-01-C        PASS            68.146                  
 54/227   MESH    MESH/NODE/TNPT/BV-02-C        PASS            69.724                  
 55/227   MESH    MESH/NODE/TNPT/BV-03-C        PASS            38.213                  
 56/227   MESH    MESH/NODE/TNPT/BV-04-C        PASS            66.597                  
 57/227   MESH    MESH/NODE/TNPT/BV-05-C        PASS            36.796                  
 58/227   MESH    MESH/NODE/TNPT/BV-06-C        PASS            34.266                  
 59/227   MESH    MESH/NODE/TNPT/BV-07-C        PASS            39.897                  
 60/227   MESH    MESH/NODE/TNPT/BV-08-C        PASS            47.624                  
 61/227   MESH    MESH/NODE/TNPT/BV-09-C        PASS            67.31                  
 62/227   MESH    MESH/NODE/TNPT/BV-10-C        PASS            35.867                  
 63/227   MESH    MESH/NODE/TNPT/BV-11-C        PASS            35.683                  
 64/227   MESH    MESH/NODE/TNPT/BV-12-C        PASS            125.009                  
 65/227   MESH    MESH/NODE/TNPT/BV-13-C        PASS            89.807                  
 66/227   MESH    MESH/NODE/TNPT/BI-01-C        PASS            66.872                  
 67/227   MESH    MESH/NODE/TNPT/BI-02-C        PASS            42.923                  
 68/227   MESH    MESH/NODE/IVU/BV-01-C         PASS            95.277                  
 69/227   MESH    MESH/NODE/IVU/BV-02-C         PASS            106.386                  
 70/227   MESH    MESH/NODE/IVU/BV-03-C         PASS            84.531                  
 71/227   MESH    MESH/NODE/IVU/BV-04-C         PASS            116.134                  
 72/227   MESH    MESH/NODE/IVU/BV-05-C         PASS            145.936                  
 73/227   MESH    MESH/NODE/IVU/BI-01-C         PASS            105.92                  
 74/227   MESH    MESH/NODE/IVU/BI-02-C         PASS            84.239                  
 75/227   MESH    MESH/NODE/IVU/BI-04-C         PASS            55.519                  
 76/227   MESH    MESH/NODE/IVU/BI-05-C         PASS            126.632                  
 77/227   MESH    MESH/NODE/IVU/BI-06-C         PASS            125.068                  
 78/227   MESH    MESH/NODE/KR/BV-01-C          PASS            128.833                  
 79/227   MESH    MESH/NODE/KR/BV-02-C          PASS            209.029                  
 80/227   MESH    MESH/NODE/KR/BV-03-C          PASS            77.244                  
 81/227   MESH    MESH/NODE/KR/BI-01-C          PASS            160.655                  
 82/227   MESH    MESH/NODE/KR/BI-02-C          PASS            84.339                  
 83/227   MESH    MESH/NODE/KR/BI-03-C          PASS            41.577                  
 84/227   MESH    MESH/NODE/KR/BI-04-C          PASS            106.15                  
 85/227   MESH    MESH/NODE/KR/BI-05-C          PASS            131.226                  
 86/227   MESH    MESH/NODE/FRND/FN/BV-01-C     PASS            52.883                  
 87/227   MESH    MESH/NODE/FRND/FN/BV-02-C     PASS            110.375                  
 88/227   MESH    MESH/NODE/FRND/FN/BV-03-C     PASS            51.865                  
 89/227   MESH    MESH/NODE/FRND/FN/BV-04-C     PASS            63.086                  
 90/227   MESH    MESH/N [...]

2021-05-18 11:07 UTC, michal-narajowski requested changes
Commit titles should start with `mesh:` or `bttester:` and then capital letter. See commit history in nimble.

2021-05-19 05:45 UTC, KKopyscinski commented on nimble/host/mesh/src/transport.c
> +	if (!k_delayed_work_pending(&rx->ack) ||
Moved this commit to https://github.com/apache/mynewt-nimble/pull/978

2021-05-19 05:50 UTC, KKopyscinski commented
@michal-narajowski Fixed commit messages and missing newlines at the end of files

2021-05-27 08:17 UTC, michal-narajowski commented on nimble/host/mesh/src/transport.h
>  uint8_t *bt_mesh_va_label_get(uint16_t addr);
Ping.

2021-05-27 08:19 UTC, michal-narajowski approved these changes

2021-05-27 08:19 UTC, merged